spring.application.name=01-student-crud
server.port=3000

spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=Anupam123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver